### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by vvaths** [ps-developers-sandbox/real-deal-doi#2]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @ajkahler
- [ ] @annack84
- [ ] @bpickens99
- [ ] @cj-Blanchard
- [ ] @danmir204
- [ ] @deepakGit00
- [ ] @devinjones18
- [ ] @lmitchell4
- [ ] @smHooper
- [ ] @vvaths
- [ ] @vyas000
- [ ] @Mosnarr
- [ ] @dlcoyle-usgs
- [ ] @mierardi

**Comment by deepakGit00** [comment]
looks good
